# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6a476b31b4c09e5d2e7322d0f30f14f9479bcf952a01d05827a257f0bc84e7bd16f665e0d6d09c300bf2b770298bbf6de6c3cbff7e9a5302d17de3112e8a7cf1

test:
  secret_key_base: dfe40183febd67bc37c92af955a71f02f558cbf205521eae14966fdd2bc7c16855d80faa8bebd8aa8d3f1cb38e379ddf60ce5f016cf1192d3793055744e2167c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
